### ISSUE TITLE
关于一个可能潜在刷物品漏洞的反馈

### ISSUE THREAD

**Issue by JiangQiYan713** [SlimefunGuguProject/SlimeTinker#47]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [x] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [x] 你没有对下载的文件内容进行任何更改
- [x] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/SlimeTinker/issues)，且没有找到相同的问题

### 问题描述

关于一个可能潜在刷物品漏洞的反馈
人为的将物品送入生物的物品栏
然后使用带有青金石模组的匠魂剑击杀
时运/抢夺效果也对放入的物品产生效果

### 复现步骤

1.首先驯服一只阿米娅/羊驼
2.给生物加上箱子，放入要刷的物品
3.用任意青金石模组匠魂工具击杀
4.这时发现放入箱子的物品也出现增多现象

此外同理也可以通过将物品人为投掷给僵尸并击杀的方法刷物品

### 预期行为

掉落物附加效果只对生物对应的战利品数影响，而对人为放入生物物品栏内的物品不产生效果

### 服务器日志

没有显示任何异常日志

### 错误报告

没有生成错误报告

### 服务端软件

Paper

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Slimefun 4.9-test-cargo-stacking_items-ff32a4a
SlimeTinker vBuild 36 zh-CN(ybw0014) (git b015afe)

### 插件版本

36

**Comment by haiman233** [comment]
这不仅仅局限于羊驼，部分空岛服务器也会出现这种bug，貌似是一种与强制死亡不掉落所冲突的bug，遇到这种行为只需要禁止世界PVP就行了

**Comment by haiman233** [comment]
最快解决方法，暂时禁用青金石模块

**Comment by ybw0014** [comment]
> 最快解决方法，暂时禁用青金石模块

模块暂时禁用不了

**Comment by ybw0014** [comment]
在新版本中，已暂时禁用击杀带箱子的生物时触发的青金石模组。

**Comment by ybw0014** [comment]
后续可能会有一个更好的解决方案。

**Comment by voila1106** [comment]
原版粘液之前解决了一个刷鞍的问题  不知道能不能参考一下那个

**Comment by JiangQiYan713** [comment]
> 原版粘液之前解决了一个刷鞍的问题 不知道能不能参考一下那个

嗯不是同一个性质 原版刷鞍是属于货运系统的bug
