### ISSUE TITLE
关于匠魂的属性问题

### ISSUE THREAD

**Issue by rouyuanTT** [SlimefunGuguProject/SlimeTinker#75]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/SlimeTinker/issues)，且没有找到相同的问题

### 问题描述

不知道有没有办法粘液匠魂中的无尽防御和无尽力量附魔这些设置或者删除

### 复现步骤

正常使用

### 预期行为

可以设置某种特性的具体参数或者是否开启

### 服务端软件

Spigot

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

23.07.22-release

### 插件版本

47

**Comment by ybw0014** [comment]
/plugins/SlimeTinker/traits.yml
