### ISSUE TITLE
在1.21运行此插件时，出现的崩溃

### ISSUE THREAD

**Issue by MinghuaChiyuan** [SlimefunGuguProject/SlimeTinker#79]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/SlimeTinker/issues)，且没有找到相同的问题

### 问题描述

我在paper端1.21版本尝试使用您提供的汉化版粘液匠魂，服务器可以正常启动，且玩家在粘液菜单中也可以看到匠魂的选项，但是点击无反应，且后台抛出一个error，因为无法正常使用鬼斩的pastes，我把error粘贴放在了附件里，slimefun文件夹error_reporter并没有文件，希望可以解决
[Uploading bc.txt…]()

### 复现步骤

在1.21paper端使用鬼斩构建站提供的粘液科技及其附属，正常启动服务器{我使用的附属列表以图片的形式放在附件
![Uploading 7192dfc8e0bc995f044b72616883828f.png…]()

### 预期行为

玩家可以正常使用粘液将魂附属

### 服务端软件

Paper

### Minecraft 版本

1.21

### Slimefun版本

![7192dfc8e0bc995f044b72616883828f](https://github.com/user-attachments/assets/191af2f8-c6a6-4806-8cd3-1f2e037e5dd9)

### 插件版本

build 50 git 1249096

**Comment by ybw0014** [comment]
尝试先更新本体的版本，你这不是最新的
