### ISSUE TITLE
插件无法运行

### ISSUE THREAD

**Issue by Lubenwei-RGB** [SlimefunGuguProject/SlimeTinker#82]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/SlimeTinker/issues)，且没有找到相同的问题

### 问题描述

核心leaves
一靠近和匠魂有关就报错
无法使用

### 复现步骤

开启服务器 并靠近匠魂

### 预期行为

插件炸了

### 服务器日志

https://paste.guizhanss.net/BFqO2

### 错误报告

https://paste.guizhanss.net/0LzKy

### 服务端软件

其他 (请在问题描述里写明)

### Minecraft 版本

1.20.4

### Slimefun版本

![image](https://github.com/user-attachments/assets/19747734-b6d4-4555-b4e6-ca7290925c83)

### 插件版本

-Build 51 (git 082a0a4)

**Comment by ybw0014** [comment]
Duplicate of #81
