### ISSUE TITLE
1.21.1无法运行，自动禁用

### ISSUE THREAD

**Issue by hseermc** [SlimefunGuguProject/SlimeTinker#83]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/SlimeTinker/issues)，且没有找到相同的问题

### 问题描述

如题
https://paste.guizhanss.net/itQAX

### 复现步骤

1.21.1安装匠魂，启动

### 预期行为

正常运行

### 错误报告

https://paste.guizhanss.net/itQAX

### 服务端软件

其他 (请在问题描述里写明)

### Minecraft 版本

1.21.1

### Slimefun版本

Slimefun vf53c2f6-Insider

### 插件版本

SlimeTinker vBuild 51 (git 082a0a4)

**Comment by ybw0014** [comment]
bot把上游更新自动合并了，动力科技还没更新

**Comment by ybw0014** [comment]
先退1-2个版本关闭自动更新

**Comment by ybw0014** [comment]
已回滚动力科技相关改动
